# generated by datamodel-codegen:
#   filename:  base.schema.yaml
#   timestamp: 2025-04-11T18:30:33+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field, RootModel, constr


class Identifier(RootModel[constr(pattern=r'^[a-zA-Z_\-]+[a-zA-Z0-9$_\-]*$')]):
    root: constr(pattern=r'^[a-zA-Z_\-]+[a-zA-Z0-9$_\-]*$') = Field(
        ...,
        description='An identifier for use within the context of a root pointer\n',
        examples=['a', 'a0', '-$', '__init__'],
        title='ethdebug/format/pointer/identifier',
    )


class EthdebugFormatPointerRegionBase(BaseModel):
    name: Optional[Identifier] = None
    location: str
