# generated by datamodel-codegen:
#   filename:  pointer/region/base.schema.yaml

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel

from .. import identifier_schema


class Location(Enum):
    stack = 'stack'
    memory = 'memory'
    storage = 'storage'
    calldata = 'calldata'
    returndata = 'returndata'
    transient = 'transient'
    code = 'code'


class EthdebugFormatPointerRegionBase(BaseModel):
    name: Optional[identifier_schema.EthdebugFormatPointerIdentifier] = None
    location: Location
