# generated by datamodel-codegen:
#   filename:  pointer/region/base.schema.yaml

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel

from ..identifier_schema import PointerIdentifier


class Location(Enum):
    stack = 'stack'
    memory = 'memory'
    storage = 'storage'
    calldata = 'calldata'
    returndata = 'returndata'
    transient = 'transient'
    code = 'code'


class PointerRegionBase(BaseModel):
    name: Optional[PointerIdentifier] = None
    location: Location
