# generated by datamodel-codegen:
#   filename:  pointer/region/base.schema.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel

from .. import identifier_schema


class EthdebugFormatPointerRegionBase(BaseModel):
    name: Optional[identifier_schema.EthdebugFormatPointerIdentifier] = None
    location: str
