# generated by datamodel-codegen:
#   filename:  pointer/region/code.schema.yaml

from __future__ import annotations

from typing import Literal

from ..scheme.slice_schema import PointerSchemeSlice
from .base_schema import PointerRegionBase


class PointerRegionCode(PointerRegionBase, PointerSchemeSlice):
    location: Literal['code']
