# generated by datamodel-codegen:
#   filename:  pointer/region/code.schema.yaml
#   timestamp: 2025-05-02T06:59:03+00:00

from __future__ import annotations

from typing import Literal

from .calldata_schema import Base, Slice


class EthdebugFormatPointerRegionCode(Base, Slice):
    location: Literal['code']


EthdebugFormatPointerRegionCode.model_rebuild()
