# generated by datamodel-codegen:
#   filename:  pointer/region/memory.schema.yaml

from __future__ import annotations

from typing import Literal

from ..scheme.slice_schema import EthdebugFormatPointerSchemeSlice
from .base_schema import EthdebugFormatPointerRegionBase


class EthdebugFormatPointerRegionMemory(
    EthdebugFormatPointerRegionBase, EthdebugFormatPointerSchemeSlice
):
    location: Literal['memory']
