# generated by datamodel-codegen:
#   filename:  pointer/region/returndata.schema.yaml
#   timestamp: 2025-05-02T06:59:03+00:00

from __future__ import annotations

from typing import Literal

from .calldata_schema import Base, Slice


class EthdebugFormatPointerRegionReturndata(Base, Slice):
    location: Literal['returndata']


EthdebugFormatPointerRegionReturndata.model_rebuild()
