# generated by datamodel-codegen:
#   filename:  pointer/region/returndata.schema.yaml

from __future__ import annotations

from typing import Literal

from ..scheme.slice_schema import EthdebugFormatPointerSchemeSlice
from .base_schema import EthdebugFormatPointerRegionBase


class EthdebugFormatPointerRegionReturndata(
    EthdebugFormatPointerRegionBase, EthdebugFormatPointerSchemeSlice
):
    location: Literal['returndata']
