# generated by datamodel-codegen:
#   filename:  pointer/region/stack.schema.yaml

from __future__ import annotations

from typing import Literal

from ..scheme.segment_schema import PointerSchemeSegment
from .base_schema import PointerRegionBase


class PointerRegionStack(PointerRegionBase, PointerSchemeSegment):
    location: Literal['stack']
