# generated by datamodel-codegen:
#   filename:  pointer/region/stack.schema.yaml

from __future__ import annotations

from typing import Literal

from ..scheme.segment_schema import EthdebugFormatPointerSchemeSegment
from .base_schema import EthdebugFormatPointerRegionBase


class EthdebugFormatPointerRegionStack(
    EthdebugFormatPointerRegionBase, EthdebugFormatPointerSchemeSegment
):
    location: Literal['stack']
