# generated by datamodel-codegen:
#   filename:  pointer/region/storage.schema.yaml

from __future__ import annotations

from typing import Literal

from ..scheme.segment_schema import EthdebugFormatPointerSchemeSegment
from .base_schema import EthdebugFormatPointerRegionBase


class EthdebugFormatPointerRegionStorage(
    EthdebugFormatPointerRegionBase, EthdebugFormatPointerSchemeSegment
):
    location: Literal['storage']
