# generated by datamodel-codegen:
#   filename:  pointer/region/storage.schema.yaml

from __future__ import annotations

from typing import Literal

from ..scheme.segment_schema import PointerSchemeSegment
from .base_schema import PointerRegionBase


class PointerRegionStorage(PointerRegionBase, PointerSchemeSegment):
    location: Literal['storage']
