# generated by datamodel-codegen:
#   filename:  pointer/region/storage.schema.yaml
#   timestamp: 2025-05-02T06:59:03+00:00

from __future__ import annotations

from typing import Literal

from .calldata_schema import Base
from .stack_schema import Segment


class EthdebugFormatPointerRegionStorage(Base, Segment):
    location: Literal['storage']
