# generated by datamodel-codegen:
#   filename:  pointer/region/transient.schema.yaml

from __future__ import annotations

from typing import Literal

from ..scheme.segment_schema import PointerSchemeSegment
from .base_schema import PointerRegionBase


class PointerRegionTransient(PointerRegionBase, PointerSchemeSegment):
    location: Literal['transient']
