# generated by datamodel-codegen:
#   filename:  id.schema.yaml
#   timestamp: 2025-04-11T18:30:32+00:00

from __future__ import annotations

from typing import Union

from pydantic import Field, RootModel


class EthdebugFormatMaterialsId(RootModel[Union[float, str]]):
    root: Union[float, str] = Field(
        ...,
        description='An opaque external ID (likely generated by compiler)',
        examples=[5, 'five'],
        title='ethdebug/format/materials/id',
    )
