# generated by datamodel-codegen:
#   filename:  materials/id.schema.yaml

from __future__ import annotations

from typing import Annotated, Union

from pydantic import Field, RootModel


class MaterialsId(RootModel[Union[float, str]]):
    root: Annotated[
        Union[float, str],
        Field(
            description='An opaque identifier for a compilation resource (such as a source\nfile or a compilation itself), typically generated by the compiler.\nValues may be numeric or string and **must** be unique within the\nscope where they appear (e.g., source IDs within a single\ncompilation).\n',
            examples=[0, '__301f3b6d85831638'],
            title='ethdebug/format/materials/id',
        ),
    ]
