# generated by datamodel-codegen:
#   filename:  materials/id.schema.yaml

from __future__ import annotations

from typing import Annotated, Union

from pydantic import Field, RootModel


class MaterialsId(RootModel[Union[float, str]]):
    root: Annotated[
        Union[float, str],
        Field(
            description='An opaque external ID (likely generated by compiler)',
            examples=[5, 'five'],
            title='ethdebug/format/materials/id',
        ),
    ]
