# generated by datamodel-codegen:
#   filename:  materials/reference.schema.yaml
#   timestamp: 2025-05-02T06:59:03+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel

from ..type.complex import alias_schema


class Type(Enum):
    compilation = 'compilation'
    source = 'source'


class EthdebugFormatMaterialsReference(BaseModel):
    id: alias_schema.Id
    type: Optional[Type] = None
