# generated by datamodel-codegen:
#   filename:  materials/reference.schema.yaml

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel

from .id_schema import MaterialsId


class Type(Enum):
    compilation = 'compilation'
    source = 'source'


class MaterialsReference(BaseModel):
    id: MaterialsId
    type: Optional[Type] = None
