# generated by datamodel-codegen:
#   filename:  materials/reference.schema.yaml

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel

from . import id_schema


class Type(Enum):
    compilation = 'compilation'
    source = 'source'


class EthdebugFormatMaterialsReference(BaseModel):
    id: id_schema.EthdebugFormatMaterialsId
    type: Optional[Type] = None
