# generated by datamodel-codegen:
#   filename:  reference.schema.yaml
#   timestamp: 2025-04-11T19:10:54+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional, Union

from pydantic import BaseModel, Field, RootModel


class Type(Enum):
    compilation = 'compilation'
    source = 'source'


class Id(RootModel[Union[float, str]]):
    root: Union[float, str] = Field(
        ...,
        description='An opaque external ID (likely generated by compiler)',
        examples=[5, 'five'],
        title='ethdebug/format/materials/id',
    )


class EthdebugFormatMaterialsReference(BaseModel):
    id: Id
    type: Optional[Type] = None
