# generated by datamodel-codegen:
#   filename:  materials/source-range.schema.yaml
#   timestamp: 2025-05-02T06:59:03+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field

from ..type.complex import alias_schema


class Range(BaseModel):
    offset: alias_schema.Value = Field(
        ..., description='Byte offset at beginning of range.\n'
    )
    length: alias_schema.Value = Field(
        ..., description='Number of bytes contained in range'
    )


class EthdebugFormatMaterialsSourceRange(BaseModel):
    compilation: Optional[alias_schema.Reference] = Field(
        None, title='Compilation reference by ID'
    )
    source: alias_schema.Reference = Field(..., title='Source reference by ID')
    range: Optional[Range] = Field(
        None,
        description='Ranges that span the entire source contents **may** omit this field\nas a shorthand. This field is otherwise **required**.\n',
        title='Bytes range within source contents',
    )
