# generated by datamodel-codegen:
#   filename:  type/complex/alias.schema.yaml

from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, Field

from .. import definition_schema, wrapper_schema


class EthdebugFormatTypeComplexAlias(BaseModel):
    class_: Literal['complex'] = Field('complex', alias='class')
    kind: Literal['alias']
    contains: wrapper_schema.EthdebugFormatTypeWrapper
    definition: Optional[definition_schema.EthdebugFormatTypeDefinition] = None
