# generated by datamodel-codegen:
#   filename:  type/complex/alias.schema.yaml

from __future__ import annotations

from typing import Annotated, Literal, Optional

from pydantic import BaseModel, Field

from ..definition_schema import TypeDefinition
from ..wrapper_schema import TypeWrapper


class TypeComplexAlias(BaseModel):
    class_: Annotated[Literal['complex'], Field(alias='class')] = 'complex'
    kind: Literal['alias']
    contains: TypeWrapper
    definition: Optional[TypeDefinition] = None
