# generated by datamodel-codegen:
#   filename:  type/complex/array.schema.yaml
#   timestamp: 2025-05-02T06:59:03+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

from . import alias_schema


class EthdebugFormatTypeComplexArray(BaseModel):
    class_: Literal['complex'] = Field('complex', alias='class')
    kind: Literal['array']
    contains: alias_schema.Wrapper
