# generated by datamodel-codegen:
#   filename:  type/complex/array.schema.yaml

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

from .. import wrapper_schema


class EthdebugFormatTypeComplexArray(BaseModel):
    class_: Literal['complex'] = Field('complex', alias='class')
    kind: Literal['array']
    contains: wrapper_schema.EthdebugFormatTypeWrapper
