# generated by datamodel-codegen:
#   filename:  type/complex/mapping.schema.yaml

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, Field

from ..wrapper_schema import TypeWrapper


class Contains(BaseModel):
    key: TypeWrapper
    value: TypeWrapper


class TypeComplexMapping(BaseModel):
    class_: Annotated[Literal['complex'], Field(alias='class')] = 'complex'
    kind: Literal['mapping']
    contains: Annotated[Contains, Field(title='Mapping key/value types')]
