# generated by datamodel-codegen:
#   filename:  type/complex/mapping.schema.yaml
#   timestamp: 2025-05-02T06:59:03+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

from . import alias_schema


class Contains(BaseModel):
    key: alias_schema.Wrapper
    value: alias_schema.Wrapper


class EthdebugFormatTypeComplexMapping(BaseModel):
    class_: Literal['complex'] = Field('complex', alias='class')
    kind: Literal['mapping']
    contains: Contains = Field(..., title='Mapping key/value types')
