# generated by datamodel-codegen:
#   filename:  type/complex/mapping.schema.yaml

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

from .. import wrapper_schema


class Contains(BaseModel):
    key: wrapper_schema.EthdebugFormatTypeWrapper
    value: wrapper_schema.EthdebugFormatTypeWrapper


class EthdebugFormatTypeComplexMapping(BaseModel):
    class_: Literal['complex'] = Field('complex', alias='class')
    kind: Literal['mapping']
    contains: Contains = Field(..., title='Mapping key/value types')
