# generated by datamodel-codegen:
#   filename:  type/complex/struct.schema.yaml

from __future__ import annotations

from typing import Annotated, List, Literal, Optional

from pydantic import BaseModel, Field

from ..definition_schema import TypeDefinition
from ..wrapper_schema import TypeWrapper


class Memberfield(TypeWrapper):
    name: Optional[str] = None


class TypeComplexStruct(BaseModel):
    class_: Annotated[Literal['complex'], Field(alias='class')] = 'complex'
    kind: Literal['struct']
    contains: List[Memberfield]
    definition: Optional[TypeDefinition] = None
