# generated by datamodel-codegen:
#   filename:  type/complex/struct.schema.yaml

from __future__ import annotations

from typing import List, Literal, Optional

from pydantic import BaseModel, Field

from .. import definition_schema
from ..wrapper_schema import EthdebugFormatTypeWrapper


class MemberField(EthdebugFormatTypeWrapper):
    name: Optional[str] = None


class EthdebugFormatTypeComplexStruct(BaseModel):
    class_: Literal['complex'] = Field('complex', alias='class')
    kind: Literal['struct']
    contains: List[MemberField]
    definition: Optional[definition_schema.EthdebugFormatTypeDefinition] = None
