# generated by datamodel-codegen:
#   filename:  type/complex/struct.schema.yaml
#   timestamp: 2025-05-02T06:59:03+00:00

from __future__ import annotations

from typing import List, Literal, Optional

from pydantic import BaseModel, Field

from . import alias_schema
from .alias_schema import Wrapper


class MemberField(Wrapper):
    name: Optional[str] = None


class EthdebugFormatTypeComplexStruct(BaseModel):
    class_: Literal['complex'] = Field('complex', alias='class')
    kind: Literal['struct']
    contains: List[MemberField]
    definition: Optional[alias_schema.Definition] = None
