# generated by datamodel-codegen:
#   filename:  type/complex/tuple.schema.yaml
#   timestamp: 2025-05-02T06:59:03+00:00

from __future__ import annotations

from typing import List, Literal, Optional

from pydantic import BaseModel, Field

from .alias_schema import Wrapper


class Element(Wrapper):
    name: Optional[str] = Field(
        None,
        description='For tuple types where positional element types are identified by name, this field **should** include this information.\nThis schema makes no restriction on whether all-or-no elements have names, and so this field may be sparse across elements of the same tuple.',
    )


class EthdebugFormatTypeComplexTuple(BaseModel):
    class_: Literal['complex'] = Field('complex', alias='class')
    kind: Literal['tuple']
    contains: List[Element]
