# generated by datamodel-codegen:
#   filename:  pointer/scheme/slice.schema.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field

from ..expression_schema import PointerExpression


class PointerSchemeSlice(BaseModel):
    offset: Annotated[
        PointerExpression,
        Field(
            description='The index of the byte (starting from zero) in the data location where\nthe slice begins.\n'
        ),
    ]
    length: Annotated[
        PointerExpression,
        Field(description='The length of the slice in number of bytes.\n'),
    ]
