# generated by datamodel-codegen:
#   filename:  pointer/scheme/slice.schema.yaml
#   timestamp: 2025-05-02T06:59:03+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from ..region import calldata_schema


class EthdebugFormatPointerSchemeSlice(BaseModel):
    offset: calldata_schema.Expression = Field(
        ...,
        description='The index of the byte (starting from zero) in the data location where\nthe slice begins.\n',
    )
    length: calldata_schema.Expression = Field(
        ..., description='The length of the slice in number of bytes.\n'
    )
