# generated by datamodel-codegen:
#   filename:  pointer/scheme/slice.schema.yaml

from __future__ import annotations

from pydantic import BaseModel, Field

from .. import expression_schema


class EthdebugFormatPointerSchemeSlice(BaseModel):
    offset: expression_schema.EthdebugFormatPointerExpression = Field(
        ...,
        description='The index of the byte (starting from zero) in the data location where\nthe slice begins.\n',
    )
    length: expression_schema.EthdebugFormatPointerExpression = Field(
        ..., description='The length of the slice in number of bytes.\n'
    )
