# generated by datamodel-codegen:
#   filename:  unsigned.schema.yaml
#   timestamp: 2025-04-11T12:46:46+00:00

from __future__ import annotations

from pydantic import Field, RootModel, conint


class EthdebugFormatDataUnsigned(RootModel[conint(ge=0)]):
    root: conint(ge=0) = Field(
        ...,
        description='A non-negative integer encoded as a JSON number.\n',
        examples=[0, 100],
        title='ethdebug/format/data/unsigned',
    )
