# generated by datamodel-codegen:
#   filename:  data/unsigned.schema.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import Field, RootModel


class DataUnsigned(RootModel[int]):
    root: Annotated[
        int,
        Field(
            description='A non-negative integer encoded as a JSON number.\n',
            examples=[0, 100],
            ge=0,
            title='ethdebug/format/data/unsigned',
        ),
    ]
