# generated by datamodel-codegen:
#   filename:  data/value.schema.yaml

from __future__ import annotations

from typing import Union

from pydantic import Field, RootModel

from . import hex_schema, unsigned_schema


class EthdebugFormatDataValue(
    RootModel[
        Union[
            unsigned_schema.EthdebugFormatDataUnsigned, hex_schema.EthdebugFormatDataHex
        ]
    ]
):
    root: Union[
        unsigned_schema.EthdebugFormatDataUnsigned, hex_schema.EthdebugFormatDataHex
    ] = Field(
        ...,
        description='A non-negative integer value, expressed either as a native JSON number or as\na `0x`-prefixed hexadecimal string.\n',
        examples=['0x0000', 2],
        title='ethdebug/format/data/value',
    )
