# generated by datamodel-codegen:
#   filename:  data/value.schema.yaml
#   timestamp: 2025-05-02T06:59:03+00:00

from __future__ import annotations

from typing import Union

from pydantic import Field, RootModel

from ..type.complex import alias_schema


class EthdebugFormatDataValue(
    RootModel[Union[alias_schema.Unsigned, alias_schema.Hex]]
):
    root: Union[alias_schema.Unsigned, alias_schema.Hex] = Field(
        ...,
        description='A non-negative integer value, expressed either as a native JSON number or as\na `0x`-prefixed hexadecimal string.\n',
        examples=['0x0000', 2],
        title='ethdebug/format/data/value',
    )
