# generated by datamodel-codegen:
#   filename:  data/value.schema.yaml

from __future__ import annotations

from typing import Annotated, Union

from pydantic import Field, RootModel

from .hex_schema import DataHex
from .unsigned_schema import DataUnsigned


class DataValue(RootModel[Union[DataUnsigned, DataHex]]):
    root: Annotated[
        Union[DataUnsigned, DataHex],
        Field(
            description='A non-negative integer value, expressed either as a native JSON number or as\na `0x`-prefixed hexadecimal string.\n',
            examples=['0x0000', 2],
            title='ethdebug/format/data/value',
        ),
    ]
