# generated by datamodel-codegen:
#   filename:  collection.schema.yaml
#   timestamp: 2025-04-11T19:10:53+00:00

from __future__ import annotations

from pydantic import BaseModel


class EthdebugFormatPointerCollection(BaseModel):
    pass
