# generated by datamodel-codegen:
#   filename:  identifier.schema.yaml
#   timestamp: 2025-04-11T12:46:46+00:00

from __future__ import annotations

from pydantic import Field, RootModel, constr


class EthdebugFormatPointerIdentifier(
    RootModel[constr(pattern=r'^[a-zA-Z_\-]+[a-zA-Z0-9$_\-]*$')]
):
    root: constr(pattern=r'^[a-zA-Z_\-]+[a-zA-Z0-9$_\-]*$') = Field(
        ...,
        description='An identifier for use within the context of a root pointer\n',
        examples=['a', 'a0', '-$', '__init__'],
        title='ethdebug/format/pointer/identifier',
    )
