# generated by datamodel-codegen:
#   filename:  pointer/identifier.schema.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import Field, RootModel


class PointerIdentifier(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description='An identifier for use within the context of a root pointer\n',
            examples=['a', 'a0', '-$', '__init__'],
            pattern='^[a-zA-Z_\\-]+[a-zA-Z0-9$_\\-]*$',
            title='ethdebug/format/pointer/identifier',
        ),
    ]
