# generated by datamodel-codegen:
#   filename:  pointer/region.schema.yaml

from __future__ import annotations

from enum import Enum
from typing import Annotated, Optional, Union

from pydantic import Field, RootModel

from .region.calldata_schema import PointerRegionCalldata
from .region.code_schema import PointerRegionCode
from .region.memory_schema import PointerRegionMemory
from .region.returndata_schema import PointerRegionReturndata
from .region.stack_schema import PointerRegionStack
from .region.storage_schema import PointerRegionStorage
from .region.transient_schema import PointerRegionTransient


class Location(Enum):
    stack = 'stack'
    memory = 'memory'
    storage = 'storage'
    calldata = 'calldata'
    returndata = 'returndata'
    transient = 'transient'
    code = 'code'


class PointerRegion(
    RootModel[
        Union[
            Pointer_Region,
            PointerRegion2,
            PointerRegion3,
            PointerRegion4,
            PointerRegion5,
            PointerRegion6,
            PointerRegion7,
        ]
    ]
):
    root: Annotated[
        Union[
            Pointer_Region,
            PointerRegion2,
            PointerRegion3,
            PointerRegion4,
            PointerRegion5,
            PointerRegion6,
            PointerRegion7,
        ],
        Field(
            description='A representation of a region of data in the EVM\n',
            examples=[
                {
                    'location': 'storage',
                    'slot': '0x0000000000000000000000000000000000000000000000000000000000000000',
                }
            ],
            title='ethdebug/format/pointer/region',
        ),
    ]


class Pointer_Region(PointerRegionStack):
    location: Optional[Location] = None


class PointerRegion3(PointerRegionStorage):
    location: Optional[Location] = None


class PointerRegion6(PointerRegionTransient):
    location: Optional[Location] = None


class PointerRegion4(PointerRegionCalldata):
    location: Optional[Location] = None


class PointerRegion7(PointerRegionCode):
    location: Optional[Location] = None


class PointerRegion2(PointerRegionMemory):
    location: Optional[Location] = None


class PointerRegion5(PointerRegionReturndata):
    location: Optional[Location] = None


PointerRegion.model_rebuild()
