# generated by datamodel-codegen:
#   filename:  region.schema.yaml
#   timestamp: 2025-04-11T19:10:53+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel


class Location(Enum):
    stack = 'stack'
    memory = 'memory'
    storage = 'storage'
    calldata = 'calldata'
    returndata = 'returndata'
    transient = 'transient'
    code = 'code'


class EthdebugFormatPointerRegion(BaseModel):
    location: Optional[Location] = None
