# generated by datamodel-codegen:
#   filename:  program/context/code.schema.yaml
#   timestamp: 2025-05-02T06:59:03+00:00

from __future__ import annotations

from pydantic import BaseModel

from ...type.complex import alias_schema


class EthdebugFormatProgramContextCode(BaseModel):
    code: alias_schema.SourceRange
