# generated by datamodel-codegen:
#   filename:  program/context/code.schema.yaml

from __future__ import annotations

from pydantic import BaseModel

from ...materials.source_range_schema import MaterialsSourceRange


class ProgramContextCode(BaseModel):
    code: MaterialsSourceRange
