# generated by datamodel-codegen:
#   filename:  program/context/code.schema.yaml

from __future__ import annotations

from pydantic import BaseModel

from ...materials import source_range_schema


class EthdebugFormatProgramContextCode(BaseModel):
    code: source_range_schema.EthdebugFormatMaterialsSourceRange
