# generated by datamodel-codegen:
#   filename:  program/context/frame.schema.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class ProgramContextFrame(BaseModel):
    frame: Annotated[str, Field(title='Relevant compilation frame')]
