# generated by datamodel-codegen:
#   filename:  program/context/frame.schema.yaml

from __future__ import annotations

from pydantic import BaseModel, Field


class EthdebugFormatProgramContextFrame(BaseModel):
    frame: str = Field(..., title='Relevant compilation frame')
