# generated by datamodel-codegen:
#   filename:  program/context/gather.schema.yaml

from __future__ import annotations

from typing import Annotated, List

from pydantic import BaseModel, Field

from ..context_schema import ProgramContext


class ProgramContextGather(BaseModel):
    gather: Annotated[
        List[ProgramContext], Field(min_length=2, title='Contexts to gather')
    ]
