# generated by datamodel-codegen:
#   filename:  program/context/gather.schema.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field

from .. import context_schema


class EthdebugFormatProgramContextGather(BaseModel):
    gather: List[context_schema.EthdebugFormatProgramContext] = Field(
        ..., min_length=2, title='Contexts to gather'
    )
