# generated by datamodel-codegen:
#   filename:  program/context/name.schema.yaml

from __future__ import annotations

from pydantic import BaseModel


class ProgramContextName(BaseModel):
    name: str
