# generated by datamodel-codegen:
#   filename:  program/context/remark.schema.yaml

from __future__ import annotations

from pydantic import BaseModel


class ProgramContextRemark(BaseModel):
    remark: str
