# generated by datamodel-codegen:
#   filename:  program/context/remark.schema.yaml
#   timestamp: 2025-05-02T06:59:03+00:00

from __future__ import annotations

from pydantic import BaseModel


class EthdebugFormatProgramContextRemark(BaseModel):
    remark: str
