# generated by datamodel-codegen:
#   filename:  remark.schema.yaml
#   timestamp: 2025-04-11T12:46:47+00:00

from __future__ import annotations

from pydantic import BaseModel


class EthdebugFormatProgramContextRemark(BaseModel):
    remark: str
