# generated by datamodel-codegen:
#   filename:  program/context.schema.yaml

from __future__ import annotations

from pydantic import BaseModel


class EthdebugFormatProgramContext(BaseModel):
    pass
