# generated by datamodel-codegen:
#   filename:  type/complex.schema.yaml

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class Kind(Enum):
    alias = 'alias'
    tuple = 'tuple'
    array = 'array'
    mapping = 'mapping'
    struct = 'struct'
    function = 'function'


class TypeComplex(BaseModel):
    kind: Kind
