# generated by datamodel-codegen:
#   filename:  complex.schema.yaml
#   timestamp: 2025-04-11T12:46:47+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class Kind(Enum):
    alias = 'alias'
    tuple = 'tuple'
    array = 'array'
    mapping = 'mapping'
    struct = 'struct'
    function = 'function'


class EthdebugFormatTypeComplex(BaseModel):
    kind: Kind
