# generated by datamodel-codegen:
#   filename:  elementary.schema.yaml
#   timestamp: 2025-04-11T12:46:48+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class Kind(Enum):
    uint = 'uint'
    int = 'int'
    bool = 'bool'
    bytes = 'bytes'
    string = 'string'
    ufixed = 'ufixed'
    fixed = 'fixed'
    address = 'address'
    contract = 'contract'
    enum = 'enum'


class EthdebugFormatTypeElementary(BaseModel):
    kind: Kind
