# generated by datamodel-codegen:
#   filename:  reference.schema.yaml
#   timestamp: 2025-04-11T19:10:54+00:00

from __future__ import annotations

from typing import Union

from pydantic import BaseModel, ConfigDict


class EthdebugFormatTypeReference(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Union[str, float]
