# generated by datamodel-codegen:
#   filename:  type/reference.schema.yaml
#   timestamp: 2025-05-02T06:59:03+00:00

from __future__ import annotations

from typing import Union

from pydantic import BaseModel, ConfigDict


class EthdebugFormatTypeReference(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Union[str, float]
