# generated by datamodel-codegen:
#   filename:  type/reference.schema.yaml

from __future__ import annotations

from typing import Union

from pydantic import BaseModel, ConfigDict


class TypeReference(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Union[str, float]
