# generated by datamodel-codegen:
#   filename:  pointer/collection/conditional.schema.yaml

from __future__ import annotations

from typing import Annotated, Optional

from pydantic import BaseModel, ConfigDict, Field

from ...pointer_schema import Pointer
from ..expression_schema import PointerExpression


class PointerCollectionConditional(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    if_: Annotated[PointerExpression, Field(alias='if')]
    then: Pointer
    else_: Annotated[Optional[Pointer], Field(alias='else')] = None


PointerCollectionConditional.model_rebuild()
