# generated by datamodel-codegen:
#   filename:  pointer/collection/conditional.schema.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field

from ... import pointer_schema
from .. import expression_schema


class EthdebugFormatPointerCollectionConditional(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    if_: expression_schema.EthdebugFormatPointerExpression = Field(..., alias='if')
    then: pointer_schema.EthdebugFormatPointer
    else_: Optional[pointer_schema.EthdebugFormatPointer] = Field(None, alias='else')


EthdebugFormatPointerCollectionConditional.model_rebuild()
