# generated by datamodel-codegen:
#   filename:  pointer/collection/conditional.schema.yaml
#   timestamp: 2025-05-02T06:59:03+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field

from ..region import calldata_schema


class Pointer(BaseModel):
    pass


class EthdebugFormatPointerCollectionConditional(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    if_: calldata_schema.Expression = Field(..., alias='if')
    then: Pointer
    else_: Optional[Pointer] = Field(None, alias='else')
