# generated by datamodel-codegen:
#   filename:  pointer/collection/group.schema.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, Field

from ... import pointer_schema


class EthdebugFormatPointerCollectionGroup(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    group: List[pointer_schema.EthdebugFormatPointer] = Field(..., min_length=1)
