# generated by datamodel-codegen:
#   filename:  pointer/collection/group.schema.yaml

from __future__ import annotations

from typing import Annotated, List

from pydantic import BaseModel, ConfigDict, Field

from ...pointer_schema import Pointer


class PointerCollectionGroup(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    group: Annotated[List[Pointer], Field(min_length=1)]


PointerCollectionGroup.model_rebuild()
