# generated by datamodel-codegen:
#   filename:  group.schema.yaml
#   timestamp: 2025-04-11T18:30:32+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, Field


class Pointer(BaseModel):
    pass


class EthdebugFormatPointerCollectionGroup(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    group: List[Pointer] = Field(..., min_length=1)
