# generated by datamodel-codegen:
#   filename:  pointer/collection/group.schema.yaml
#   timestamp: 2025-05-02T06:59:03+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, Field

from . import conditional_schema


class EthdebugFormatPointerCollectionGroup(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    group: List[conditional_schema.Pointer] = Field(..., min_length=1)
