# generated by datamodel-codegen:
#   filename:  pointer/collection/reference.schema.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field

from ..identifier_schema import PointerIdentifier


class PointerCollectionReference(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    template: Annotated[PointerIdentifier, Field(title='Template identifier')]
