# generated by datamodel-codegen:
#   filename:  pointer/collection/reference.schema.yaml

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from .. import identifier_schema


class EthdebugFormatPointerCollectionReference(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    template: identifier_schema.EthdebugFormatPointerIdentifier = Field(
        ..., title='Template identifier'
    )
