# generated by datamodel-codegen:
#   filename:  pointer/collection/reference.schema.yaml

from __future__ import annotations

from typing import Annotated, Dict, Optional

from pydantic import BaseModel, ConfigDict, Field

from ..identifier_schema import PointerIdentifier


class PointerCollectionReference(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    template: Annotated[PointerIdentifier, Field(title='Template identifier')]
    yields: Annotated[
        Optional[Dict[str, PointerIdentifier]],
        Field(
            description='Maps region names produced by the template to new names for use\noutside the template. Unmapped region names pass through unchanged.\nWhen omitted, all regions keep their original names.\n',
            title='Region name mapping',
        ),
    ] = None
