# generated by datamodel-codegen:
#   filename:  reference.schema.yaml
#   timestamp: 2025-04-11T19:10:53+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr


class Identifier(RootModel[constr(pattern=r'^[a-zA-Z_\-]+[a-zA-Z0-9$_\-]*$')]):
    root: constr(pattern=r'^[a-zA-Z_\-]+[a-zA-Z0-9$_\-]*$') = Field(
        ...,
        description='An identifier for use within the context of a root pointer\n',
        examples=['a', 'a0', '-$', '__init__'],
        title='ethdebug/format/pointer/identifier',
    )


class EthdebugFormatPointerCollectionReference(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    template: Identifier = Field(..., title='Template identifier')
