# generated by datamodel-codegen:
#   filename:  pointer/collection/scope.schema.yaml
#   timestamp: 2025-05-02T06:59:03+00:00

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, ConfigDict, Field, constr

from ..region import calldata_schema
from . import conditional_schema


class EthdebugFormatPointerCollectionScope(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    define: Dict[
        constr(pattern=r'^[a-zA-Z_\-]+[a-zA-Z0-9$_\-]*$'), calldata_schema.Expression
    ] = Field(..., title='Mapping of variables to expression value')
    in_: conditional_schema.Pointer = Field(..., alias='in')
