# generated by datamodel-codegen:
#   filename:  pointer/collection/scope.schema.yaml

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, ConfigDict, Field, constr

from ... import pointer_schema
from .. import expression_schema


class EthdebugFormatPointerCollectionScope(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    define: Dict[
        constr(pattern=r'^[a-zA-Z_\-]+[a-zA-Z0-9$_\-]*$'),
        expression_schema.EthdebugFormatPointerExpression,
    ] = Field(..., title='Mapping of variables to expression value')
    in_: pointer_schema.EthdebugFormatPointer = Field(..., alias='in')
