# generated by datamodel-codegen:
#   filename:  pointer/collection/templates.schema.yaml

from __future__ import annotations

from typing import Annotated, Dict

from pydantic import BaseModel, ConfigDict, Field

from ...pointer_schema import Pointer
from ..template_schema import PointerTemplate


class PointerCollectionTemplates(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    templates: Annotated[
        Dict[str, PointerTemplate],
        Field(title='Mapping of template names to template definitions'),
    ]
    in_: Annotated[Pointer, Field(alias='in')]
