# generated by datamodel-codegen:
#   filename:  info/resources.schema.yaml
#   timestamp: 2025-05-02T06:59:03+00:00

from __future__ import annotations

from typing import Dict, Optional

from pydantic import BaseModel, Field

from .. import info_schema
from ..program import context_schema


class EthdebugFormatInfoResources(BaseModel):
    types: Dict[str, context_schema.Type] = Field(
        ...,
        description='A collection of types by name identifier.\n',
        title='Types by name',
    )
    pointers: Dict[str, info_schema.Template] = Field(
        ...,
        description='A collection of pointer templates by name identifier.\n',
        title='Pointer templates by name',
    )
    compilation: Optional[info_schema.Compilation] = None
