# generated by datamodel-codegen:
#   filename:  type/elementary/address.schema.yaml

from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, Field


class EthdebugFormatTypeElementaryAddress(BaseModel):
    class_: Literal['elementary'] = Field('elementary', alias='class')
    kind: Literal['address']
    payable: Optional[bool] = Field(
        None,
        description='If this field is omitted, this type represents an address whose payability is not known.',
    )
