# generated by datamodel-codegen:
#   filename:  type/elementary/address.schema.yaml

from __future__ import annotations

from typing import Annotated, Literal, Optional

from pydantic import BaseModel, Field


class TypeElementaryAddress(BaseModel):
    class_: Annotated[Literal['elementary'], Field(alias='class')] = 'elementary'
    kind: Literal['address']
    payable: Annotated[
        Optional[bool],
        Field(
            description='If this field is omitted, this type represents an address whose payability is not known.'
        ),
    ] = None
