# generated by datamodel-codegen:
#   filename:  address.schema.yaml
#   timestamp: 2025-04-11T19:10:54+00:00

from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, Field


class EthdebugFormatTypeElementaryAddress(BaseModel):
    class_: Literal['elementary'] = Field('elementary', alias='class')
    kind: Literal['address']
    payable: Optional[bool] = Field(
        None,
        description='If this field is omitted, this type represents an address whose payability is not known.',
    )
