# generated by datamodel-codegen:
#   filename:  bool.schema.yaml
#   timestamp: 2025-04-11T18:30:34+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class EthdebugFormatTypeElementaryBool(BaseModel):
    class_: Literal['elementary'] = Field('elementary', alias='class')
    kind: Literal['bool']
