# generated by datamodel-codegen:
#   filename:  type/elementary/bool.schema.yaml

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class EthdebugFormatTypeElementaryBool(BaseModel):
    class_: Literal['elementary'] = Field('elementary', alias='class')
    kind: Literal['bool']
