# generated by datamodel-codegen:
#   filename:  type/elementary/bool.schema.yaml

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, Field


class TypeElementaryBool(BaseModel):
    class_: Annotated[Literal['elementary'], Field(alias='class')] = 'elementary'
    kind: Literal['bool']
