# generated by datamodel-codegen:
#   filename:  type/elementary/bytes.schema.yaml

from __future__ import annotations

from typing import Annotated, Literal, Optional

from pydantic import BaseModel, Field

from ...data.unsigned_schema import DataUnsigned


class TypeElementaryBytes(BaseModel):
    class_: Annotated[Literal['elementary'], Field(alias='class')] = 'elementary'
    kind: Literal['bytes']
    size: Annotated[
        Optional[DataUnsigned],
        Field(
            description='The number of bytes in the bytes string. If this field is omitted, this type is the dynamic bytes string type.'
        ),
    ] = None
