# generated by datamodel-codegen:
#   filename:  bytes.schema.yaml
#   timestamp: 2025-04-11T18:30:34+00:00

from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, Field, RootModel, conint


class Unsigned(RootModel[conint(ge=0)]):
    root: conint(ge=0) = Field(
        ...,
        description='A non-negative integer encoded as a JSON number.\n',
        examples=[0, 100],
        title='ethdebug/format/data/unsigned',
    )


class EthdebugFormatTypeElementaryBytes(BaseModel):
    class_: Literal['elementary'] = Field('elementary', alias='class')
    kind: Literal['bytes']
    size: Optional[Unsigned] = Field(
        None,
        description='The number of bytes in the bytes string. If this field is omitted, this type is the dynamic bytes string type.',
    )
