# generated by datamodel-codegen:
#   filename:  type/elementary/bytes.schema.yaml
#   timestamp: 2025-05-02T06:59:03+00:00

from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, Field

from ..complex import alias_schema


class EthdebugFormatTypeElementaryBytes(BaseModel):
    class_: Literal['elementary'] = Field('elementary', alias='class')
    kind: Literal['bytes']
    size: Optional[alias_schema.Unsigned] = Field(
        None,
        description='The number of bytes in the bytes string. If this field is omitted, this type is the dynamic bytes string type.',
    )
