# generated by datamodel-codegen:
#   filename:  type/elementary/bytes.schema.yaml

from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, Field

from ...data import unsigned_schema


class EthdebugFormatTypeElementaryBytes(BaseModel):
    class_: Literal['elementary'] = Field('elementary', alias='class')
    kind: Literal['bytes']
    size: Optional[unsigned_schema.EthdebugFormatDataUnsigned] = Field(
        None,
        description='The number of bytes in the bytes string. If this field is omitted, this type is the dynamic bytes string type.',
    )
