# generated by datamodel-codegen:
#   filename:  type/elementary/enum.schema.yaml
#   timestamp: 2025-05-02T06:59:03+00:00

from __future__ import annotations

from typing import List, Literal, Optional

from pydantic import BaseModel, Field

from ..complex import alias_schema


class EthdebugFormatTypeElementaryEnum(BaseModel):
    class_: Literal['elementary'] = Field('elementary', alias='class')
    kind: Literal['enum']
    values: List = Field(
        ...,
        description='The allowed values of an enum. This format makes no restriction on which values are allowed here.',
    )
    definition: Optional[alias_schema.Definition] = None
