# generated by datamodel-codegen:
#   filename:  type/elementary/enum.schema.yaml

from __future__ import annotations

from typing import Annotated, List, Literal, Optional

from pydantic import BaseModel, Field

from ..definition_schema import TypeDefinition


class TypeElementaryEnum(BaseModel):
    class_: Annotated[Literal['elementary'], Field(alias='class')] = 'elementary'
    kind: Literal['enum']
    values: Annotated[
        List,
        Field(
            description='The allowed values of an enum. This format makes no restriction on which values are allowed here.'
        ),
    ]
    definition: Optional[TypeDefinition] = None
