# generated by datamodel-codegen:
#   filename:  type/elementary/enum.schema.yaml

from __future__ import annotations

from typing import List, Literal, Optional

from pydantic import BaseModel, Field

from .. import definition_schema


class EthdebugFormatTypeElementaryEnum(BaseModel):
    class_: Literal['elementary'] = Field('elementary', alias='class')
    kind: Literal['enum']
    values: List = Field(
        ...,
        description='The allowed values of an enum. This format makes no restriction on which values are allowed here.',
    )
    definition: Optional[definition_schema.EthdebugFormatTypeDefinition] = None
