# generated by datamodel-codegen:
#   filename:  type/elementary/fixed.schema.yaml

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, Field


class TypeElementaryFixed(BaseModel):
    class_: Annotated[Literal['elementary'], Field(alias='class')] = 'elementary'
    kind: Literal['fixed']
    bits: Annotated[int, Field(ge=8, le=256, multiple_of=8.0)]
    places: Annotated[
        int,
        Field(
            description='How many decimal places, implying that a raw value `v` of this type should be interpreted as `v / (10**places)`',
            ge=1,
            le=80,
        ),
    ]
