# generated by datamodel-codegen:
#   filename:  type/elementary/int.schema.yaml

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, Field


class TypeElementaryInt(BaseModel):
    class_: Annotated[Literal['elementary'], Field(alias='class')] = 'elementary'
    kind: Literal['int']
    bits: Annotated[int, Field(ge=8, le=256, multiple_of=8.0)]
