# generated by datamodel-codegen:
#   filename:  string.schema.yaml
#   timestamp: 2025-04-11T12:46:47+00:00

from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, Field


class EthdebugFormatTypeElementaryString(BaseModel):
    class_: Literal['elementary'] = Field('elementary', alias='class')
    kind: Literal['string']
    encoding: Optional[str] = 'utf-8'
