# generated by datamodel-codegen:
#   filename:  type/elementary/string.schema.yaml

from __future__ import annotations

from typing import Annotated, Literal, Optional

from pydantic import BaseModel, Field


class TypeElementaryString(BaseModel):
    class_: Annotated[Literal['elementary'], Field(alias='class')] = 'elementary'
    kind: Literal['string']
    encoding: Optional[str] = 'utf-8'
