# generated by datamodel-codegen:
#   filename:  type/elementary/string.schema.yaml

from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, Field


class EthdebugFormatTypeElementaryString(BaseModel):
    class_: Literal['elementary'] = Field('elementary', alias='class')
    kind: Literal['string']
    encoding: Optional[str] = 'utf-8'
