# generated by datamodel-codegen:
#   filename:  ufixed.schema.yaml
#   timestamp: 2025-04-11T18:30:34+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, conint


class EthdebugFormatTypeElementaryUfixed(BaseModel):
    class_: Literal['elementary'] = Field('elementary', alias='class')
    kind: Literal['ufixed']
    bits: conint(ge=8, le=256, multiple_of=8)
    places: conint(ge=1, le=80) = Field(
        ...,
        description='How many decimal places, implying that a raw value `v` of this type should be interpreted as `v / (10**places)`',
    )
