# generated by datamodel-codegen:
#   filename:  uint.schema.yaml
#   timestamp: 2025-04-11T12:46:47+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, conint


class EthdebugFormatTypeElementaryUint(BaseModel):
    class_: Literal['elementary'] = Field('elementary', alias='class')
    kind: Literal['uint']
    bits: conint(ge=8, le=256, multiple_of=8)
