# generated by datamodel-codegen:
#   filename:  info.schema.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel

from . import program_schema
from .materials import compilation_schema


class EthdebugFormatInfo(BaseModel):
    programs: List[program_schema.EthdebugFormatProgram]
    compilation: compilation_schema.EthdebugFormatMaterialsCompilation
