# generated by datamodel-codegen:
#   filename:  pointer.schema.yaml
#   timestamp: 2025-04-11T19:10:52+00:00

from __future__ import annotations

from pydantic import BaseModel


class EthdebugFormatPointer(BaseModel):
    pass
