# generated by datamodel-codegen:
#   filename:  program.schema.yaml

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field

from .materials import reference_schema, source_range_schema
from .program import context_schema, instruction_schema


class Environment(Enum):
    call = 'call'
    create = 'create'


class Contract(BaseModel):
    name: Optional[str] = None
    definition: source_range_schema.EthdebugFormatMaterialsSourceRange


class EthdebugFormatProgram(BaseModel):
    compilation: Optional[reference_schema.EthdebugFormatMaterialsReference] = Field(
        None,
        description='A reference to the compilation as an `{ "id": ... }` object.\n',
        title='Compilation reference by ID',
    )
    contract: Contract
    environment: Environment = Field(
        ...,
        description='Whether this bytecode is for contract creation or runtime calls.\n',
        title='Bytecode execution environment',
    )
    context: Optional[context_schema.EthdebugFormatProgramContext] = Field(
        None,
        description='The context known to exist prior to the execution of the first\ninstruction in the bytecode.\n',
    )
    instructions: List[instruction_schema.EthdebugFormatProgramInstruction] = Field(
        ..., description='The full array of instructions for the bytecode.\n'
    )
