# generated by datamodel-codegen:
#   filename:  type.schema.yaml
#   timestamp: 2025-04-11T12:46:48+00:00

from __future__ import annotations

from pydantic import BaseModel


class EthdebugFormatType(BaseModel):
    pass
